# Generated by Django 3.2 on 2021-04-13 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autokey', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('deskripsi', models.TextField()),
                ('status', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Confrouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('deskripsi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contohmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('desk', models.TextField()),
                ('value', models.IntegerField()),
                ('pub_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=30)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('kecepatan_download', models.IntegerField(blank=True)),
                ('kecepatan_upload', models.IntegerField(blank=True)),
                ('pub_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manualcommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255)),
                ('output', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routerapp.routerm')),
            ],
        ),
        migrations.CreateModel(
            name='Automationon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routerapp.automation')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routerapp.routerm')),
            ],
        ),
    ]
