# Generated by Django 3.1.7 on 2021-03-24 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routerapp', '0002_automationon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationon',
            name='status',
        ),
    ]
