# Generated by Django 3.1.7 on 2021-03-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerapp', '0003_remove_automationon_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationon',
            name='create_at',
            field=models.TimeField(auto_created=True, default='00:00'),
        ),
    ]
