# Generated by Django 3.1.7 on 2021-03-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerapp', '0004_automationon_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationon',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
