# Generated by Django 3.1.7 on 2021-04-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routerapp', '0007_auto_20210325_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualcommand',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
