# Generated by Django 2.2.17 on 2020-11-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netauto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contohmodel',
            name='pub_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
