# Generated by Django 2.2.17 on 2021-01-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netauto', '0002_contohmodel_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('pub_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
