# Generated by Django 2.2.17 on 2021-01-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netauto', '0003_routerm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerm',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
