# Generated by Django 2.2.17 on 2021-01-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netauto', '0004_auto_20210109_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerm',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
