# Generated by Django 2.2.17 on 2021-01-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netauto', '0005_auto_20210109_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Confrouter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('deskripsi', models.CharField(max_length=50)),
            ],
        ),
    ]
