# Generated by Django 2.2.17 on 2021-01-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netauto', '0006_automation_confrouter'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
