# Generated by Django 2.2.17 on 2021-01-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netauto', '0008_auto_20210122_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerm',
            name='kecepatan_internet',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
    ]
