# Generated by Django 2.2.17 on 2021-01-30 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netauto', '0009_routerm_kecepatan_internet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manualcommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=50)),
                ('output', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netauto.Automation')),
            ],
        ),
    ]
