# Generated by Django 2.2.17 on 2021-01-30 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netauto', '0010_manualcommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualcommand',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netauto.Routerm'),
        ),
    ]
